### ISSUE TITLE
Sol website: homepage status bar

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#11]
Let's update this, shall we?  : ) 

<img width="1133" alt="screen shot 2018-01-18 at 10 05 21 pm" src="https://user-images.githubusercontent.com/8788316/35136999-cce79c00-fc9b-11e7-928c-31a51fba8ece.png">

**Comment by prismofeverything** [comment]
Tooooootally holy orb

**Comment by prismofeverything** [comment]
Now says: Shipping retail orders! Estimated shipping about a week (depending on location)
