### ISSUE TITLE
Stripe Conf Email: change promise for tracking info

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#20]
Problem: current order confirmation promises tracking information. Funagain no longer sends out tracking information...at least not reliably. 

Solution:
Consider changing the promise for tracking information to read something like:
"We process orders weekly. If you live in the USA, you can expect delivery within 2-3 weeks of placing your order. If you live in CA, the EU or RoW you can expect tracking information within 7-10 days of placing your order."

Currently the email reads:
Dear Kristofer Pelletier,
Thank you for your order of Sol: Last Days of a Star!
Your total with the game and shipping together comes to 70 USD.
We process orders weekly, so you should receive tracking information from our shipping partner within 6 business days.
We will ship it to this address:

1015 south jennings avenue
apt 1409
City: fort worth
State: Texas
Country: US
ZIP: 76104

Let us know if you have any questions! (you can reply directly to this email)

With great gratitude,
Elephant Laboratories
Ryan, Sean and Jodi

https://elephantlaboratories.com

**Comment by prismofeverything** [comment]
Okay, I just copied your suggestion directly in. No tracking information for US people!
