### ISSUE TITLE
Website: "Buy" page copy update

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#22]
Problem: 
Copy on the Buy page is outdated.

Solution:
Consider updating to something like 
"Every copy of Sol: Last Days of a Star include all Kickstarter stretch goals. Order yours below!
Questions? You can contact us directly at mothership@elephantlaboratories.com "

Currently reads:
PURCHASE SOL
Sol: Last Days of a Star is now shipping all preorders! Orders made from here on out are direct purchases.

**Comment by prismofeverything** [comment]
Hmmm I look at the page and it says

    CURRENT STATUS: Shipping retail orders! Estimated shipping about a week (depending on location)   More »

Ah now I see, you are talking about the `PURCHASE` page. fixing........

**Comment by prismofeverything** [comment]
Okay, done. Will be going up in the next update (today)
