### ISSUE TITLE
BGB invoicing for two shipments

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#23]
We are going to ship another 12 games to Bosco at Board Game Bliss.
Because we are shipping(8) games from S&L and (4) from Funagain, he needs two separate invoices for his importing records, as they ship to different locations.

Please create two invoices:
1. (8) games at the agreed-upon price of $45/box (consider if we need to add anything for S&L's shipping/handling costs??) going to:
BoardGameBliss
8865 Woodbine Ave, Unit D3-148
Markham, ON L3R 5G1
416-275-9869
boardgamebliss@gmail.com

2. (4) games at the agreed-upon price of $45/box, going to the same location as his past orders.

**Comment by prismofeverything** [comment]
Created and sent!
