### ISSUE TITLE
Stripe: Auto reply email needs updating

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#3]
When an order is received, the buyer receives the message below. Can you update it to remove the language around pre-orders? Maybe replace it with "We process orders weekly, so you should receive tracking information from our shipping partner within 6 business days." ??

Dear Harish Narayanan,
Thank you for your order of Sol: Last Days of a Star!
Your total with the game and shipping together comes to 70 USD.
Shipping for retail pre-orders begins in August, 2017.
We will ship it to this address:

6802 Linden Ave N
City: Seattle
State: Washington
Country: US
ZIP: 98103

Let us know if you have any questions! (you can reply directly to this email)

With great gratitude,
Elephant Laboratories
Ryan, Sean and Jodi

https://elephantlaboratories.com

**Comment by prismofeverything** [comment]
Good catch. Done.
