### ISSUE TITLE
BGG Description needs editing

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#5]
Funagain pulled their description straight from our BGG page, which made me notice some critical errors. 
Below, I've highlighted what I think would be bare minimum edits we should make on the BGG page. But please consider if you want to rework it more thoroughly (like changing "ships" to "sundivers"?). I think it reads just fine, but could also probably use some freshening up: ) 

Once we have this finalized on BGG page, I can send the edited version to Nick at Funagain to update their page. 

LIGHTLY EDITED VERSION (my proposed changes are bold and italicized):

In recent years, the Sun has become increasingly unstable, to the point where experts claim it could go supernova at any moment. The various inhabitants of the planets in this solar system are launching one last effort to save themselves, which involves building a final Ark to propel a small selection of their people into deep space. This requires a great deal of energy, and in a final ironic twist, the only source of such great energy is the dying star itself. In the process of extracting and transmitting the energy required to save themselves, they will be compounding the instability of the Sun and hastening the end of their worlds.

Sol: Last Days of a Star is a board game **_for one to_** five players where each player represents a different planetary effort to transmit as much energy from the Sun back to their Ark so they can to escape the solar system before the Sun explodes!

The board represents the solar environment: two layers of orbit around the Sun (Upper and Lower Orbit), and three layers within the Sun itself (the Convective, Radiative, and Core). The deeper **_you take actions_**, the higher your rewards, but the faster the instability of the Sun is increased. Your Mothership rotates slowly in orbit around the Sun, and this is the only place your ships can launch from to perform useful tasks in the solar environment. You can either convert ships into stations or use the ships to activate yours and other players' stations. If you activate your own stations you get the full reward, while activating other player's stations you split the reward with the owner. You gain energy by activating **_Energy Nodes_**, and you use this energy to either activate **_Ship Foundries_** to build new ships (which you need since you are constantly losing ships by converting them into new stations) or activate **_Transmit Towers_** to transmit the energy back to your Ark to turn into Momentum (which is ultimately how your Ark will escape). But you cannot enter the Sun without converting ships into **_Solar Gates_** which span the high energy membranes separating one **_layer of the sun_** from the next.

You must carefully manage your time and resources in order to transmit the most energy back to your Ark before the Sun is lost forever. With any luck, some small collection of your last planetary residents will escape the solar system before it is engulfed by the oncoming supernova!

**Comment by prismofeverything** [comment]
Oh my! That is pretty bad. I will update that now.

Do you know if Nick is waiting on us for something there? The funagain site still says "preorder".

**Comment by prismofeverything** [comment]
Done.

**Comment by metaporpoise** [comment]
Thanks for knocking this out. I sent on to Nick and asked about the pre-order status. I am confident he is not waiting on anything from us, but maybe he does that since they haven't outright purchased the games? Like, once they get an order, they have to check our inventory maybe?? I cc'd you on the note to Nick.
