### ISSUE TITLE
Reviews: new material for site updates

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#6]
This can be a repository for links to good reviews we may want to use/quote in the future:

October 2017
http://dailyworkerplacement.com/2017/10/25/sol-last-days-of-a-star/

August 2017
https://boardgamegeek.com/blogpost/68756/august-cruellest-month
https://geekdad.com/2017/08/sol-last-days-of-a-star/

July 2017
http://dicehateme.com/2017/07/the-crowded-table-post-origins-edition/

**Comment by prismofeverything** [comment]
Done!
