### ISSUE TITLE
Videos: new material for Media page

### ISSUE THREAD

**Issue by metaporpoise** [prismofeverything/elephantlaboratories#8]
For whenever we may update the site: 

July 2017
https://www.orderofgamers.com/the-joy-of-unboxing-sol-last-days-of-a-star/
http://www.belloflostsouls.net/2017/07/tabletop-spotlight-sol.html
https://youtu.be/q2wbguu5VAA (the Kwarenteen unboxing)
https://youtu.be/yNslcUSEv-8 (the Esoteric Order of Gamers unboxing)

**Comment by prismofeverything** [comment]
Done!
